CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS links (
    id uuid UNIQUE PRIMARY KEY DEFAULT uuid_generate_v4(),
    short VARCHAR(20) UNIQUE NOT NULL,
    original TEXT NOT NULL,
    clicks INT8 NOT NULL DEFAULT 0,
    time TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

